# Generated by Django 4.1.7 on 2023-03-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codigo_vestimenta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='familiares1_festejados',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='familiares1_foto',
            field=models.ImageField(blank=True, null=True, upload_to='family_album'),
        ),
        migrations.AddField(
            model_name='profile',
            name='familiares2_festejados',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='familiares2_foto',
            field=models.ImageField(blank=True, null=True, upload_to='family_album'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='festejados',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='link_regalos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lugar_ceremonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lugar_fiesta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mesa_regalos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='testigos_festejados',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
