# Generated by Django 4.1.7 on 2023-03-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_codigo_vestimenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link_invitacion',
            field=models.IntegerField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
