# Generated by Django 4.1.7 on 2023-03-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_link_invitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link_invitacion',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
