# Generated by Django 4.1.7 on 2023-03-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_link_invitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link_invitacion',
        ),
    ]
