# Generated by Django 4.1.7 on 2023-03-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=3228045617, null=True, unique=True),
        ),
    ]
