# Generated by Django 4.1.7 on 2023-03-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='catalogo_invitacion',
            field=models.CharField(choices=[('INVITACION', 'Invitacion'), ('INVITACION', 'Invitacion1'), ('INVITACION', 'Invitacion2'), ('INVITACION', 'Invitacion3'), ('INVITACION', 'Invitacion4'), ('INVITACION', 'Invitacion5')], default='Invitacion', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=8887889817, null=True, unique=True),
        ),
    ]
