# Generated by Django 4.1.7 on 2023-03-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_catalogo_invitacion_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='catalogo_invitacion',
            field=models.CharField(choices=[('Invitacion', 'Invitacion'), ('Invitacion1', 'Invitacion1'), ('Invitacion2', 'Invitacion2'), ('Invitacion3', 'Invitacion3'), ('Invitacion4', 'Invitacion4'), ('Invitacion5', 'Invitacion5')], default='Invitacion', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=4500595649, null=True, unique=True),
        ),
    ]
