# Generated by Django 4.1.7 on 2023-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_catalogo_invitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='template_invitacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=7647115758, null=True, unique=True),
        ),
    ]
