# Generated by Django 4.1.7 on 2023-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_template_invitacion_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=5858148749, null=True, unique=True),
        ),
    ]
