# Generated by Django 4.1.7 on 2023-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_referencia_pago_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referencia_pago',
            field=models.BigIntegerField(default=17511, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=1904365940, null=True, unique=True),
        ),
    ]
