# Generated by Django 4.1.7 on 2023-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_referencia_pago_alter_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referencia_pago',
        ),
        migrations.AddField(
            model_name='profile',
            name='ref_pago',
            field=models.BigIntegerField(default=67553, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=7786894899, null=True, unique=True),
        ),
    ]
