# Generated by Django 4.1.7 on 2023-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_profile_referencia_pago_profile_ref_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref_pago',
            field=models.BigIntegerField(default=35085, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=3163896814, null=True, unique=True),
        ),
    ]
