# Generated by Django 4.1.7 on 2023-03-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_profile_ref_pago_alter_profile_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref_pago',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
