# Generated by Django 4.1.7 on 2023-03-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_profile_ref_pago_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='template_invitacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
