# Generated by Django 4.1.7 on 2023-03-29 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0027_alter_profile_template_invitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
