# Generated by Django 4.1.7 on 2023-03-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0002_alter_usergallery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.ImageField(upload_to='invitation_catalog')),
                ('catalog_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=180)),
            ],
        ),
    ]
