# Generated by Django 4.1.7 on 2023-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0004_invitationcatalog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcatalog',
            name='category',
            field=models.CharField(choices=[('FIESTA', 'Fiesta'), ('EVENTO', 'Evento'), ('INFANTIL', 'Infantil')], default='Fiesta', max_length=20),
        ),
    ]
